### ISSUE TITLE
[Question] Setting Widget Limit

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#13]
Hi,

These are the default widget limits for movies/shows in FENtastic:
![image](https://user-images.githubusercontent.com/29895680/230465824-0771313e-4f7f-4b0c-9b15-9e64fdb68317.png)

And I have default Fen navigation settings:
![image](https://user-images.githubusercontent.com/29895680/230465961-6e6bf852-5056-42bc-991c-b97a1af99ce5.png)

Currently, for example in "Movies/Shows --> Trending" - I have 20 items, and then Next Page button:
![image](https://user-images.githubusercontent.com/29895680/230467798-9f28b2f2-3823-4e1c-aaa9-bceb37642240.png)

I have tried to play with skin + Fen settings but I'm a bit lost, how do I see in the Skin widgets only 10 items and then "Next Page" button?

**Comment by ivarbrandt** [comment]
Go into Fen settings > Navigation > under Content you'll see 'Paginate Lists When Available'. Set that to Both. Then set the 'Widgets Item Limit' to 10. Set the 'Addon Item Limit' to whatever you choose.

Finally, make sure the 'Widget limit' in Skin settings > Options is set to any number greater than 11. This is because you set the limit in Fen to 10 items plus the Next Page item.

**Comment by TwilightMercy** [comment]
> Go into Fen settings > Navigation > under Content you'll see 'Paginate Lists When Available'. Set that to Both. Then set the 'Widgets Item Limit' to 10. Set the 'Addon Item Limit' to whatever you choose.
> 
> Finally, make sure the 'Widget limit' in Skin settings > Options is set to any number greater than 11. This is because you set the limit in Fen to 10 items plus the Next Page item.

I don't see the "Next page" button:
![image](https://user-images.githubusercontent.com/29895680/230510160-ba3c7e25-dc24-4342-b430-59f35f2c9279.png)


**Fen settings:**
![image](https://user-images.githubusercontent.com/29895680/230510076-543edeb1-e652-414d-beed-e7ea401849b8.png)


**Skin Settings:**
![image](https://user-images.githubusercontent.com/29895680/230510125-f81ae464-f212-49a0-8a60-35b16a8cfb69.png)

**Comment by ivarbrandt** [comment]
Almost there! Increase the Widget limit for movies/shows and episodes in Skin settings to 21 so you'll be able to see the Next Page item.

**Comment by TwilightMercy** [comment]
I saw the first comment of increasing the skin settings to 21 - I do see now the Next page button - but I have 20 widgets for trending movies, not 10 : )

**Comment by ivarbrandt** [comment]
>  saw the first comment of increasing the skin settings to 21 - I do see now the Next page button - but I have 20 widgets for trending movies, not 10 : )

That makes sense.

> What is the logic for combining the numbers of Fen+skin settings?

This is from a Reddit comment where someone else asked me the same thing:

There are adjustable widget limits for movies/shows and episodes. Keep in mind that limits set by any skin is only useful for a local Kodi library. If you want to limit the widgets from an addon in order to reduce loading times then set those limits in the addon. The skin will limit addon widgets displayed but the addon still takes the time to load those widgets. For example if you set the limit in the skin to 10 and your addon loads 30 widgets, it will still load 30 widgets even though you'll only be able to see 10.

For example you could set the limits in the skin to 100, limits in Fen to 30, so you'll see all 30 widgets from Fen plus the next page. However if you set the limit in the skin to 15 and the limit in Fen to 20, you'll only be able to see 15 items.

**Comment by TwilightMercy** [comment]
I understand better now, my goal is to shorten widgets load time on Kodi start.

So that's why I want to reduce the widgets limit in the Skin from 20 per row, to 10. But it will still load more than 10 in the background and the speed will be the same?

Can I somehow improve the performance? while keeping "Next Page" button, and loading 10 widgets instead of 20 per page

**Comment by TwilightMercy** [comment]
I tried to configure:

![image](https://user-images.githubusercontent.com/29895680/230562057-77f2ebb0-d518-4df3-b134-3af0f366632e.png)


Fen:

![image](https://user-images.githubusercontent.com/29895680/230562107-a47262b7-48f8-4da9-8e39-b1785947c503.png)



Not seeing next page button

**Comment by ivarbrandt** [comment]
> Now both widgets has 10 items, but Fen "Widgets item limit" only applies to the bottom list:

This is exactly why the default limits in the skin are set to 21. All TMDb lists are set to 20 items per page. TMDB lists cannot be changed so they are unaffected by skin or addon limits. For a more uniform experience, set the widget limit in Fen to 20 and the skin to 21. This way you'll see the 'Next Page' item on every widget.

> The reason is that many of my build users have medium Android TV device.

20 items per widget shouldn't make much of an impact on loading times vs 10 items per widget.

**Comment by TwilightMercy** [comment]
> 
> This is exactly why the default limits in the skin are set to 21. All TMDb lists are set to 20 items per page. TMDB lists cannot be changed so they are unaffected by skin or addon limits. For a more uniform experience, set the widget limit in Fen to 20 and the skin to 21. This way you'll see the 'Next Page' item on every widget.

I see, I wish there was a way to limit TMDb lists to custom number.
I'll have to "live" with that haha.


> 20 items per widget shouldn't make much of an impact on loading times vs 10 items per widget.

From 20 items to 1- items per widget - for multiple widgets lists on low Android TV devices wouldn't it improve performance?
At least it will for non-TMDB lists, but most of the skin is TMDB list, dam.. : )

**Comment by ivarbrandt** [comment]
Set it to 20 and see how it goes.

**Comment by TwilightMercy** [comment]
> Set it to 20 and see how it goes.

My Final Settings:

![image](https://user-images.githubusercontent.com/29895680/230625170-0ea5e0e6-331a-41f7-bb4f-73810836991e.png)

![image](https://user-images.githubusercontent.com/29895680/230625216-acb5f9e0-eb2f-4dc0-b1ac-ab1e67330549.png)




Works good for non-TMDB lists.
