### ISSUE TITLE
[Issue/Request] - Bring Back Highlighting For Current Selected Item

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#16]
Hi,
Your latest update 1.0.6 is blast.

I've noticed that in this version the blue color highligthing frame is gone when standing on a widget, same applies for Favourites page.
Screenshots:

**FENtastic 1.0.5:**
![image](https://user-images.githubusercontent.com/29895680/230705125-cbe88bd7-6b4d-46db-90b3-96e425b8687d.png)

**FENtastic 1.0.6:**
![image](https://user-images.githubusercontent.com/29895680/230705175-12d0b7ed-70cb-491e-bbf6-3046c96e0889.png)

What is the reason for that? and can it be brought back? it's a bit confusing to navigate without it : )

Thanks!

**Comment by ivarbrandt** [comment]
The reason it is gone is because that was the only workaround I could find to work with the new widget scrolling behavior.
Otherwise, the first item of every widget would be auto-highlighted every time Kodi starts or the back button is hit and the first item in the list is out of the visible frame.

This is why I moved the progress that would appear when focused on each widget item to the InfoPanel.

It's easy to know where you are in every widget though because the item that is focused will always be the closest one to the InfoPanel unless you are at the last 3 items of the list. Also the item that is focused will always appear larger(zoomed in) than unfocused items.

The only way I will bring it back is if I figure out how to not have it auto-highlight the first item in the list. Or enough people agree with you and say they don't like the changes. And even then I might not change it because I like the changes.

**Comment by TwilightMercy** [comment]
> The reason it is gone is because that was the only workaround I could find to work with the new widget scrolling behavior. Otherwise, the first item of every widget would be auto-highlighted every time Kodi starts or the back button is hit and the first item in the list is out of the visible frame.
> 
> This is why I moved the progress that would appear when focused on each widget item to the InfoPanel.
> 
> It's easy to know where you are in every widget though because the item that is focused will always be the closest one to the InfoPanel unless you are at the last 3 items of the list. Also the item that is focused will always appear larger(zoomed in) than unfocused items.
> 
> The only way I will bring it back is if I figure out how to not have it auto-highlight the first item in the list. Or enough people agree with you and say they don't like the changes. And even then I might not change it because I like the changes.

I see, I didn't noticed the scrolling changes - it is way smoother and comfortable than the previous behavior.
So the blue highlighting actually doesn't matter that much with the new scrolling behavior.

Only thing if possible - to keep the blue highlighting for "Favourites" menu, (In addition to Movies/Shows widgets, In my build I'm using Favourites for some add-ons and tools shortcuts for my users). Example:

![image](https://user-images.githubusercontent.com/29895680/230711242-b689cd5c-896b-4111-b236-6fa86d9df22d.png)

**Comment by ivarbrandt** [comment]
I will add it back in for every widget that doesn't use the InfoPanel.

**Comment by TwilightMercy** [comment]
Hi friend,

Trying my luck again, since some time has passed -

The current widget scrolling behavior (which is - the current item you stand on is always the closest one to InfoPanel) is great.

Is there a way now to bring back the blue highlighting border for the current item? 

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/780bb4c3-163d-4eb3-bc1d-7515889e6c47)




Thanks for your work

**Comment by ivarbrandt** [comment]
I've tried to figure this out because I want it back too lol. Unfortunately I haven't been able to figure it out. From the research I've done on this topic, it looks like it's a Kodi bug.

**Comment by TwilightMercy** [comment]
I see :(
Maybe making the current selected item poster a little bigger is possible? So it will be noticeable in the eye

**Comment by ivarbrandt** [comment]
I'm gonna try to figure it out again later this weekend.

**Comment by TwilightMercy** [comment]
Hi, how did it went?

**Comment by ivarbrandt** [comment]
No luck. Pretty sure it is a Kodi bug at this point.
