### ISSUE TITLE
[Question] Category Widget Scrolling Behavior

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#30]
Hi,

Question regarding the widget scrolling behaviour,

For Poster/Landscape/LandscapeInfo widgets - as you said in previous issues - the item that is focused will always be the closest one to the InfoPanel (unless it's the end of the list)

For category widgets - it seems that it's not the case. The focus just goes right to the next button. Should it behave like this?

**Screenshot:**
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/f8254469-02d3-47cc-87a9-15632fc6eef6)

**Comment by ivarbrandt** [comment]
Yes, it should behave like this. Otherwise it wouldn't be able to the blue frame when focused. 

The category widgets have a different scrolling behavior because they don't provide any info to the InfoPanel. And that scrolling behavior allows me to use the blue frame without the issues that present themselves when using the scrolling behavior that the main widgets use.

**Comment by ivarbrandt** [comment]
I don't like that behavior at all. I'll be leaving it as is unless I can figure out the blue frame issue.

**Comment by TwilightMercy** [comment]
You mean you don't like the old behavior or the new one?

Because I find the new behavior more comfortable (the one that the widgets are currently using, not the category widgets)

**Comment by ivarbrandt** [comment]
I don't like the category widgets not showing the blue frame. Because for stacked category widgets for example, if the blue frame isn't there how is the user going to know what is selected? I mean they can activate the widget countdown timer but if it is less than a second (like I have it), then that won't really help.

**Comment by TwilightMercy** [comment]
>if the blue frame isn't there how is the user going to know what is selected

The same as the new scrolling behavior  - the current category item is the closest one to InfoPanel, always stays on left.

So it's the same scrolling behavior for all type of widgets (even though I also prefer the blue frame)

**Comment by ivarbrandt** [comment]
Nah I'm leaving it as is. Unless, like I said, I can figure out the damn blue frame lol.

**Comment by TwilightMercy** [comment]
Good luck 👍🏻
