### ISSUE TITLE
User Widget Files Storage Location

### ISSUE THREAD

**Issue by DevGeniusCode** [ivarbrandt/skin.fentastic#35]
Thank you for your valuable work!

I've observed that the user files, containing their list of widgets (e.g., script-fentastic-widget_movies/tvshow.xml), are currently being saved in the xml addon folder instead of the userdata folder. Consequently, upon reinstallation, the favorite list gets deleted.

Request:
If it is possible for all the widgets that are defined and all the settings to be only in userdata and not in the addon itself.

**Comment by ivarbrandt** [comment]
> Consequently, upon reinstallation, the favorite list gets deleted.

Re-installation of the skin or Kodi itself? What is this 'favorites list' you're referring to?

The XML files in the skin (script-fentastic-widget_movies/tvshow.xml) cannot be moved. They need to stay with the rest of skin XMLs otherwise the skin wouldn't be able to read and display them.

The XMLs are built from what is stored in the database and that is stored in the userdata folder.
