### ISSUE TITLE
Request - Movies/shows synopsis on main screen

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#4]
Hi,
amazing skin! really fast and great

I don't know if it is possible - to see movies/shows synopsis as a widget. similar to default "Poster" view type in Kodi:

![image](https://user-images.githubusercontent.com/29895680/227797529-4c82c7f5-ef8e-4d96-b47e-4cf6c4eadcce.png)

Thank you for this FENtastic skin!

**Comment by ivarbrandt** [comment]
Are you asking me to add the ability to display info for widgets on the homescreen? Or are you asking me to change the home widgets to something like the screenshot you provided?

**Comment by TwilightMercy** [comment]
I think the second option (maybe not change, but to add another widget view type).

What do you mean by the first option?

**Comment by ivarbrandt** [comment]
> I think the second option (maybe not change, but to add another widget view type)

I don't want to add that widget type because those posters are so big that only one or two would show on the home screen. I don't really see the point of that. Plus, it wouldn't fit with the overall flow of the home screen widgets.

> What do you mean by the first option?

I mean do you want me to add some kind of info panel for the home screen widgets? Something like the panel on the left side of this view:

![Screenshot_20230325-161058](https://user-images.githubusercontent.com/54084201/227802670-7c16b1fd-88e7-4bea-9363-c03e7f769e8b.png)

**Comment by TwilightMercy** [comment]
I see. And yes, it look good! of course if possible and not impacting performance.

**Comment by ivarbrandt** [comment]
I'll add it for the next update.

**Comment by TwilightMercy** [comment]
Thank you very much!

**Comment by ivarbrandt** [comment]
Completed for next update.

**Comment by TwilightMercy** [comment]
Thank you, any settings change required?

**Comment by ivarbrandt** [comment]
Nope. I've made it the default on the home screen so there isn't a settings changed required.

**Comment by TwilightMercy** [comment]
Thank you, can changelog.txt be updated? : D
