### ISSUE TITLE
unmatched parentheses error

### ISSUE THREAD

**Issue by kodifitzwell** [ivarbrandt/skin.fentastic#56]
hello.  I was testing your skin with my addon and I noticed some errors.
```
error <general>: unmatched parentheses in ListItem.Duration(h
error <general>: unmatched parentheses in ListItem.Duration(m
error <general>: unmatched parentheses in ListItem.Duration(h
error <general>: unmatched parentheses in ListItem.Duration(m
error <general>: unmatched parentheses in string.isequal(listitem.dbtype,episode
```
ver `1.0.16a` in line 735/736/767 of `variables.xml` there are a few closing `)` missing after `ListItem.Duration(h` and `ListItem.Duration(m` and `(ListItem.DBtype,episode`.  
fix should be:
```
<variable name="_Runtime">
	<value condition="!String.IsEmpty(ListItem.Duration) + !Skin.HasSetting(Enable.AlternateInfo)">$INFO[ListItem.Duration(h),[COLOR button_focus][B] • [/B][/COLOR],&#160;hr]&#160;$INFO[ListItem.Duration(m),,&#160;mins]</value>
	<value condition="!String.IsEmpty(ListItem.Duration) + Skin.HasSetting(Enable.AlternateInfo)">$INFO[ListItem.Duration(h),[COLOR button_focus][B]Runtime: [/B][/COLOR],&#160;hr]&#160;$INFO[ListItem.Duration(m),,&#160;mins][CR]</value>
</variable>
...
	<value condition="!ListItem.IsCollection + String.IsEqual(ListItem.DBtype,episode)">$VAR[_Aired]$VAR[_Mpaa]$VAR[_Network]$VAR[_RuntimeEpisodes]$VAR[_Endsat][CR]$VAR[_Plot][CR]</value>
```
you might also notice `&#160;` in there.  its a personal preference but I did not like the line breaks between the seasons and duration units.  the `&#160;` acts a non breaking space.  I did it for `_TotalSeasons`, `_Runtime` and `_RuntimeEpisodes`.  the diff is in the images below.  I don't really like the way the end time breaks either, but didn't really look too much into if that is editable yet, as I suspect that it is not.
![capture1](https://github.com/ivarbrandt/skin.fentastic/assets/105136042/5bbadbb4-a402-4b10-b2e6-e92440f63db9)
![capture2](https://github.com/ivarbrandt/skin.fentastic/assets/105136042/e8fbf1bf-be78-452d-94e2-6e2fdffc1049)

**Comment by ivarbrandt** [comment]
Thanks for letting me know about the missing parentheses. They showed up red on my IDE but had no effect on whether or not the $INFO for the ListItem was displayed so I didn't really think it was much of a problem.

As for the non breaking space, that's really cool and useful. I did not know you could do that. Thank you.

I'm going to leave them out though because if I started adding non breaking spaces then the format will start to approach that of the alternate InfoPanel. And that something I don't want as I want it to take up the whole line even if it gets broken up.

The alternate InfoPanel will be available in version `1.0.17`, which I'm about to push up.

It'll look like this:

![shows](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/03821393-124d-4a98-962c-e4c511290bda)
