### ISSUE TITLE
Fen error at skin launch/reload when trakt account isn't connected

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#6]
Hi,

After installing clean Kodi 20.1 (Windows),
Instaling Fen, then Installing FENtastic from your repo. 

I saw that FENtastic is coming with default preconfigured widgets for Movies/Shows in these files:
script-FENtastic-widget_movies.xml
script-FENtastic-widget_tvshows.xml

However, when initaly loading the skin on first install, I get "Fen error", and the trakt related widgets won't load (because Fen isn't connected to trakt). Only when connecting trakt account and reloading skin all widgets are load.

Log:
https://paste.kodi.tv/kodatepuqu.kodi

Screenshot:
![image](https://user-images.githubusercontent.com/29895680/228952619-aeafb8d9-ea1e-4545-87bf-a7fc37c37dc2.png)

**Comment by ivarbrandt** [comment]
> I saw that FENtastic is coming with default preconfigured widgets for Movies/Shows in these files

They aren't preconfigured widgets. Those are the widgets that I use in my setup. They should automatically delete themselves upon first install of the skin though. That way you can set up your own widgets. If they don't, (which seems to be your case) go into Skin Settings > Main menu items > click Remake menus and widgets > Go back to the home screen and your Movie and Show section should be gone. Then you can go back in to the settings to set up your widgets.

> when initaly loading the skin on first install, I get "Fen error", and the trakt related widgets won't load

This is because the widgets I have in my setup use Trakt, so FEN will throw an error if Trakt is not configured. Clearing the widgets the way I showed you should fix this issue.

**Comment by TwilightMercy** [comment]
I see, thank you

**Comment by ivarbrandt** [comment]
You're welcome. 

Is it working correctly now?

**Comment by TwilightMercy** [comment]
Yes!
