### ISSUE TITLE
Selectbox toggle?

### ISSUE THREAD

**Issue by cp3817** [ivarbrandt/skin.fentastic#69]
Hi, I have a request/question. Would it be possible to add a toggle to choose between an on-screen select box with normal sized font like in the previous version of FENtastic and the new style select box where it's just large, bold font? It's really just for personal preference. Or is it just a case of getting used to it the way it is? I'll include two screenshots so you can hopefully understand what I mean in case I'm not making sense.
![Screenshot 2023-09-17 230001](https://github.com/ivarbrandt/skin.fentastic/assets/145298022/bd0d0885-f2d4-4df4-9b1e-7ff9fb2a1c19)
![Screenshot 2023-09-17 230201](https://github.com/ivarbrandt/skin.fentastic/assets/145298022/493ee25f-0799-4bdd-a66b-74102e4ab18b)

**Comment by lewk-io** [comment]
I agree. Alternatively it'd be great if we could get some font size settings. 

I think that would help with this (being able to change the highlighted text size back to match the other font sizes) but it would also be good if we could get some font size settings for the left main menu as well because that is particularly huge as well.

(also the alignment of the kodi logo, power/settings/search and main menu not all aligning to the left is bug bare of mine)

**Comment by ivarbrandt** [comment]
No, I do not want to go down this route. If you prefer the look of the previous version of FENtastic, then download it [here](https://github.com/ivarbrandt/skin.fentastic/issues/68#issue-1897464882).
