### ISSUE TITLE
Kodi 21 Omega Compatability

### ISSUE THREAD

**Issue by 10ck** [ivarbrandt/skin.fentastic#80]
There are lots of users on already on Kodi 21 Beta 1 as it supports Dolby Vision etc, just wondering if you're aware of this: 

https://github.com/xbmc/xbmc/pull/23927

As we don't want to be caught out where we can't use this skin when the upgrade to 5.17.0 is forced.

Changes also discussed here on the forum:
https://forum.kodi.tv/showthread.php?tid=372280

Happy to test if need be. Thanks!

**Comment by ivarbrandt** [comment]
I appreciate you bringing this to my attention.

I'm not going to update the skin itself until the stable version of Kodi 21 is released. I can however bump the GUI version so that it doesn't break for Kodi 21 users. However, from what I can see GUI version 5.17.0 isn't backwards compatible yet correct?

So would this mean that if I bump the GUI version the skin would break for everyone on Nexus?

**Comment by syneoa** [comment]
I'm running it on latest beta of Kodi Omega for Windows, looks good to me although I installed it within beta and not migrated from previous versions so I don't know how it behaves in that scenario.. Skin is beautifull btw, fast and just what I need, thanks for this!

**Comment by ivarbrandt** [comment]
> "Every skin supporting favourites needs to switch to use MyFavourites.xml for Omega instead of DialogFavourites.xml.
We will remove DialogFavourites.xml for Omega. Replacement is MyFavourites.xml, which is available since Nexus."

This is done.

> check the log for other issues I've noticed like:

These aren't issues that will affect the function of the skin. 

> Might also be worthwhile creating an Omega branch for testing now?

Nah like I said, any other major changes to the skin for Omega will be done after a stable release. I will test bumping the GUI so that current Omega users continue to be able to use the skin.

**Comment by 10ck** [comment]
> 
> This is done.
> 
Thanks!

> > check the log for other issues I've noticed like:
> 
> These aren't issues that will affect the function of the skin.
> 
> > Might also be worthwhile creating an Omega branch for testing now?
> 
> Nah like I said, any other major changes to the skin for Omega will be done after a stable release. I will test bumping the GUI so that current Omega users continue to be able to use the skin.

Cool, sounds good, there's a already a few hundred of us in our Android DolbyVision group with Beta1 who are willing to help with tests!!! 

Don't forget to keep an eye on the Estuary git (if you're not already), to see what's changing as I'm sure not everything is getting documented on the forum:

https://github.com/xbmc/xbmc/commits/master/addons/skin.estuary

Thanks again for this great skin! 🥇

**Comment by TwilightMercy** [comment]
> there's a already a few hundred of us in our Android DolbyVision group with Beta1 who are willing to help with tests!!!

If possible, I would love to join :)

**Comment by ivarbrandt** [comment]
I tried bumping the GUI version and it ended up breaking the skin for Nexus users. So at this time I'm going to stay put. I will update it later after there is a stable release of Omega.

**Comment by 10ck** [comment]
> I tried bumping the GUI version and it ended up breaking the skin for Nexus users. So at this time I'm going to stay put. I will update it later after there is a stable release of Omega.

Yes, the bump would break now as it's for Beta 2 release. 

Better to test then with these minimum changes mentioned that Nexus already supports.

Cheers!

**Comment by Better-Red** [comment]
Hi,

First and foremost, thanks for all you've done with Fentastic.

It's just a suggestion, but have you considered updating your repo with an Omega branch? Your addon.xml would look something like this:

<addon id="repository.ivarbrandt" name="ivarbrandt's Repository" version="x.x.x" provider-name="Ivar Brandt">
    <extension point="xbmc.addon.repository" name="ivarbrandt's Repository">
        <dir>
            <info compressed="false">https://raw.githubusercontent.com/ivarbrandt/repository.ivarbrandt/master/repo/zips/addons.xml</info>
            <checksum>https://raw.githubusercontent.com/ivarbrandt/repository.ivarbrandt/master/repo/zips/addons.xml.md5</checksum>
            <datadir zip="true">https://raw.githubusercontent.com/ivarbrandt/repository.ivarbrandt/master/repo/zips/</datadir>
        </dir>
		<dir minversion="20.9.0">
            <info compressed="false">https://raw.githubusercontent.com/ivarbrandt/repository.ivarbrandt/omega/repo/zips/addons.xml</info>
            <checksum>https://raw.githubusercontent.com/ivarbrandt/repository.ivarbrandt/omega/repo/zips/addons.xml.md5</checksum>
            <datadir zip="true">https://raw.githubusercontent.com/ivarbrandt/repository.ivarbrandt/omega/repo/zips/</datadir>
        </dir>
    </extension>
    <extension point="xbmc.addon.metadata">
        <summary>ivarbrandt's Repository</summary>
        <description>Kodi repository for the FENtastic skin and other projects</description>
        <disclaimer></disclaimer>
        <platform>all</platform>
        <assets>
            <icon>icon.png</icon>
            <fanart>fanart.jpg</fanart>
        </assets>
    </extension>
</addon>

Then you could release test versions of an Omega compatible skin and also not break Fentastic for users who stay with Nexus when Omega is stable.  I'm using Nexus as my main platform, but a fork of Omega Beta 2 for when we're having a movie night because of Dolby Vision.

As I say, just a suggestion, I'm not interfering and thank you again.
